nora: 

  DATA_DIR: "/nfs/data/nii/data1/Analysis/GPUnet/ANALYSIS_incontext/SegFM3D/data"
  RESULTS_DIR: "/nfs/data/nii/data1/Analysis/GPUnet/ANALYSIS_incontext/SegFM3D/results"
  NNINT_CKPT_DIR : "/nfs/norasys/notebooks/camaret/model_checkpoints/nnint"

meta: 

  DATA_DIR: "/work/dlclarge2/ndirt-SegFM3D/segfm3d_nora_team/data"
  RESULTS_DIR: "/work/dlclarge2/ndirt-SegFM3D/segfm3d_nora_team/results"
  NNINT_CKPT_DIR : "/work/dlclarge2/ndirt-SegFM3D/model_checkpoints/nnint"